enum Workout {
// Shoulder
  ArnoldDumbbellPress,
  OverheadPress,
  SeatedDumbbellPress,
  LogPress,
  OneArmStandingDumbbellPress,
  PushPress,
  FrontDumbbellRaise,
  LateralRaise,
  RearDeltDumbbellRaise,
  FacePull,
  RearDeltFly,
  // Triceps
  TricepsExtension,
  CloseGripBenchPress,
  OverheadTricepsExtension,
  Skullcrusher,
  TricepsDip,
  RopePushDown,
  VBarPushDown,
  // Biceps
  BarbellCurl,
  CableCurl,
  DumbbellCurl,
  ConcentrationCurl,
  HammerCurl,
  PreacherCurl,
  InclineDumbbellCurl,
  MachineCurl,
  // Chest
  CableCrossover,
  DeclineBenchPress,
  BenchPress,
  DumbbellFly,
  InclineBenchPress,
  InclineDumbbellFly,
  MachineFly,
  // Back
  BarbellRow,
  BarbellShrug,
  DumbbellShrug,
  ChinUp,
  Deadlift,
  DumbbellRow,
  GoodMorning,
  HammerStrengthRow,
  LatPulldown,
  PendlayRow,
  PullUp,
  RackPull,
  SeatedCableRow,
  CablePushdown,
  // Legs
  BarbellFrontSquat,
  BarbellGluteBridge,
  BarbellSquat,
  DonkeyCalfRaise,
  GluteHamRaise,
  LegExtension,
  LegPress,
  LegCurl,
  RomanianDeadlift,
  SeatedCalfRaise,
  StandingCalfRaise,
  StiffLeggedDeadlift,
  SumoDeadlift,
  // Abs
  AbWheelRollout,
  CableCrunch,
  Crunch,
  DeclineCrunch,
  DragonFlag,
  HangingKneeRaise,
  HangingLegRaise,
  Plank,
  SidePlank,
}
